{
 "title": "UPS",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Home",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-home-main\"}"
    }
   ]
  },
  {
   "title": "Home Server",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-home-server\"}"
    }
   ]
  },
  {
   "title": "Office",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-office\"}"
    }
   ]
  },
  {
   "title": "Home",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-home-main\"}",
     "legendFormat": "[{{model}}]  Status"
    }
   ]
  },
  {
   "title": "Home Server",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-home-server\"}",
     "legendFormat": "[{{model}}]  Status"
    }
   ]
  },
  {
   "title": "Office",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apcupsd_ups_status{job=\"apcupsdexporter-office\"}",
     "legendFormat": "[{{model}}]  Status"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apcupsd_ups_load_percent AND apcupsd_battery_volts != 0",
     "legendFormat": "{{ups_name}}: {{model}}"
    }
   ]
  },
  {
   "title": "Battery %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_charge_percent AND apcupsd_battery_volts != 0",
     "legendFormat": "{{ups_name}}"
    },
    {}
   ]
  },
  {
   "title": "Battery 12V",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_volts > 0 AND apcupsd_battery_volts < 16",
     "legendFormat": "{{ups_name}}"
    }
   ]
  },
  {
   "title": "Battery 24V",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_volts > 16", "legendFormat": "{{ups_name}}" }
   ]
  },
  {
   "title": "On Battery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds AND apcupsd_battery_volts != 0",
     "legendFormat": "{{ups_name}}"
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds AND apcupsd_battery_volts != 0",
     "legendFormat": "{{ups_name}}"
    }
   ]
  },
  {
   "title": "Line V",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "apcupsd_line_volts AND apcupsd_battery_volts != 0",
     "legendFormat": "{{ups_name}}"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "apcupsd_internal_temp > 0 AND apcupsd_internal_temp != 29.2",
     "legendFormat": "{{ups_name}}"
    }
   ]
  }
 ]
}